'use client';
import { useEffect, useRef, useState } from 'react';
import { Heart, Moon, Sun, Music2, CloudRain, Sparkles, Coffee, Leaf, Mail, Copy, Settings2, Footprints, HandHeart, BedDouble, Sofa, X, Check, Volume2, VolumeX } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { initialRoom, type Room, type Person } from '@/lib/room';
import RoomChat from '@/components/room-chat';
const descriptions:Record<string,string>={idle:'A little space, just for us.',hug:'Stay here a little longer.',kiss:'Distance has nothing on this.',cuddle:'My favorite place is next to you.',dance:'Just us and our own little rhythm.',sleep:'Goodnight, my favorite person.',tea:'Two warm cups. All the time in the world.'};
export default function Home(){
 const [chatOpen,setChatOpen]=useState(false);
 const [room,setRoom]=useState<Room>(initialRoom),[person,setPerson]=useState<Person>('boy'),[key,setKey]=useState(''),[status,setStatus]=useState('Opening our room…'),[busy,setBusy]=useState(false),[modal,setModal]=useState(''),[draft,setDraft]=useState(''),[names,setNames]=useState(initialRoom.names),[sound,setSound]=useState(false),[notice,setNotice]=useState(''),[loaded,setLoaded]=useState(false);
 const roomRef=useRef(room),keyRef=useRef(''),personRef=useRef<Person>('boy'),serial=useRef(false);
 useEffect(()=>{roomRef.current=room;personRef.current=person},[room,person]);
 useEffect(()=>{let k=location.hash.slice(1);if(!/^[a-f0-9]{64}$/.test(k)){k=localStorage.getItem('our-room-key')||'';if(!/^[a-f0-9]{64}$/.test(k))k=Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');history.replaceState(null,'','#'+k);}localStorage.setItem('our-room-key',k);keyRef.current=k;setKey(k);const p=localStorage.getItem('our-room-person');if(p==='girl')setPerson('girl');
 let live=true;const load=async()=>{if(serial.current||document.hidden)return;try{const res=await fetch('/api/room',{headers:{'x-room-key':k},cache:'no-store'});const data=await res.json() as {state:Room;error?:string};if(!res.ok)throw Error(data.error);if(live&&!serial.current){setRoom(prev=>data.state.revision>=prev.revision?data.state:prev);setLoaded(true);setStatus('Saved · shared room');}}catch{if(live)setStatus('Connection lost · retrying');}};load();const timer=setInterval(load,2500);return()=>{live=false;clearInterval(timer)};
 },[]);
 async function act(action:string,payload?:unknown){if(serial.current||!keyRef.current)throw Error('Please wait for the room.');serial.current=true;setBusy(true);setStatus('Saving…');try{const res=await fetch('/api/room',{method:'POST',headers:{'Content-Type':'application/json','x-room-key':keyRef.current},body:JSON.stringify({action,payload,person:personRef.current})});const data=await res.json() as {state:Room;error?:string};if(!res.ok)throw Error(data.error||'Could not save.');setRoom(data.state);roomRef.current=data.state;setLoaded(true);setStatus('Saved · shared room');return data.state;}catch(e){setStatus('Not saved · please try again');setNotice((e as Error).message);throw e;}finally{serial.current=false;setBusy(false)}}
 function go(action:string,payload?:unknown){void act(action,payload).catch(()=>{});}
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(t)},[notice]);
 useEffect(()=>{if(!sound||!room.music)return;const ctx=new AudioContext();const melody=[261.63,329.63,392,493.88,440,392,329.63,293.66];let n=0;const play=()=>{const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='sine';osc.frequency.value=melody[n++%melody.length];gain.gain.setValueAtTime(0,ctx.currentTime);gain.gain.linearRampToValueAtTime(.055,ctx.currentTime+.08);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+1.6);osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+1.7)};play();const timer=setInterval(play,650);return()=>{clearInterval(timer);void ctx.close()}},[sound,room.music]);
 useEffect(()=>{const c=(document as any).modelContext;if(!c?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(c.registerTool({name:'perform_room_action',description:'Perform and save a hug, kiss, cuddle, dance, sleep, wake, or room light change for both characters.',inputSchema:{type:'object',properties:{action:{type:'string',enum:['hug','kiss','cuddle','dance','sleep','wake','lights']}},required:['action'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(!input||!['hug','kiss','cuddle','dance','sleep','wake','lights'].includes(input.action))throw Error('Invalid room action');const r=await act(input.action);return {mode:r.mode,lights:r.lights,saved:true};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[]);
 async function share(){try{await navigator.clipboard.writeText(location.href);setNotice('Room link copied. Send it to your person.')}catch{setModal('share')}}
 function choose(p:Person){if(p==='boy')setChatOpen(true);setPerson(p);personRef.current=p;localStorage.setItem('our-room-person',p)}
 function walk(e:React.MouseEvent<HTMLDivElement>){const b=e.currentTarget.getBoundingClientRect();let x=(e.clientX-b.left)/b.width*100,y=(e.clientY-b.top)/b.height*100;if(x>=24&&x<=76&&y>=53&&y<=82)go('move',{x,y});}
 const pose=room.mode==='sleep'?3:['hug','kiss','dance'].includes(room.mode)?1:['cuddle','tea'].includes(room.mode)?2:0;
 const tools=[{a:'lights',label:room.lights?'Lights on':'Lights off',I:Sun,on:room.lights},{a:'fairy',label:'Fairy lights',I:Sparkles,on:room.fairy},{a:'rain',label:'Rainy night',I:CloudRain,on:room.rain},{a:'music',label:'Music box',I:Music2,on:room.music},{a:'candles',label:'Candles',I:Heart,on:room.candles}];
 return <main className="app-shell"><header className="topbar"><a className="brand" href="#" onClick={e=>e.preventDefault()}><span className="brand-icon"><Heart size={22} fill="currentColor"/></span><span>our little room<span className="brand-sub">somewhere with you</span></span></a><div className="top-actions"><span className={'save-status '+(!loaded?'pending':'')}><i/>{status}</span><button className="soft-button" onClick={share}><Copy size={15}/><span>Invite my person</span></button><button className="icon-button" aria-label="Room settings" onClick={()=>{setNames(room.names);setModal('settings')}}><Settings2 size={19}/></button></div></header>
 <div className="room-layout"><section className="room-main"><div className="scene-heading"><div><span className="eyebrow">OUR OWN LITTLE CORNER OF THE WORLD</span><h1>Home is here.</h1></div><span className="night-pill"><Moon size={14}/> {room.mode==='sleep'?'Sweet dreams':'A cozy night in'}</span></div>
 <div className={'scene '+(!room.lights?'lights-off ':'')+(room.fairy?'fairy-on ':'')+(room.mode==='dance'?'dancing':'')} onClick={walk} aria-label="Interactive pixel room. Select a character and click the open floor to move.">
 <img className="room-art" src="/room.png" alt="A cozy isometric pixel apartment with a moonlit kitchen, soft sofa, and double bed" draggable={false}/><div className="night-shade"/>
 {room.fairy&&<div className="fairy-glow"/>}{room.candles&&<div className="candle-glow"/>}
 {room.rain&&<div className="rain" aria-hidden="true">{Array.from({length:35},(_,i)=><i key={i} style={{left:(i*29%100)+'%',animationDelay:(i%9)*-.21+'s',animationDuration:((i%3)*.2+.7)+'s'}}/>)}</div>}
 {(['boy','girl'] as Person[]).map(p=><button key={p} className={'character '+p+' '+(person===p?'selected ':'')+(room.mode==='sleep'?'sleeping':'')} style={{left:room[p].x+'%',top:room[p].y+'%'}} onClick={e=>{e.stopPropagation();choose(p)}} aria-label={'Control '+room.names[p]}><img src={'/sprites/'+p+'-'+pose+'.png'} alt={room.names[p]} draggable={false}/><span className="character-name">{room.names[p]}</span>{room.mode==='sleep'&&<b className="zzz">z z z</b>}</button>)}
 {['hug','kiss','cuddle'].includes(room.mode)&&<div className="love-particles" style={{left:((room.boy.x+room.girl.x)/2)+'%',top:(Math.min(room.boy.y,room.girl.y)-15)+'%'}}><Heart fill="currentColor"/><span>♥</span><span>♥</span></div>}
 {room.tea&&<span className="tea-steam">~ ~</span>}{room.music&&<span className="music-notes">♪ ♫ ♪</span>}
 <button className="hotspot bed" aria-label="Go to sleep together" title="Sleep together" onClick={e=>{e.stopPropagation();go(room.mode==='sleep'?'wake':'sleep')}}><BedDouble size={17}/></button>
 <button className="hotspot sofa" aria-label="Cuddle on the sofa" title="Cuddle" onClick={e=>{e.stopPropagation();go('cuddle')}}><Sofa size={17}/></button>
 <button className="hotspot kitchen" aria-label="Make tea for two" title="Tea for two" onClick={e=>{e.stopPropagation();go('tea')}}><Coffee size={17}/></button>
 <button className="hotspot plant" aria-label="Water our plant" title="Water our plant" onClick={e=>{e.stopPropagation();go('plant');setNotice('A little water, a little love.')}}><Leaf size={17}/></button>
 <button className="hotspot letter" aria-label="Read and leave notes" title="Our notes" onClick={e=>{e.stopPropagation();setModal('notes')}}><Mail size={17}/>{room.notes.length>0&&<i/>}</button>
 </div><div className="scene-caption"><span><Footprints size={15}/> Pick your character, then tap the floor to wander.</span><button onClick={()=>setSound(!sound)} className="sound-button" aria-label={sound?'Mute sound':'Enable sound'}>{sound?<Volume2 size={16}/>:<VolumeX size={16}/>}Sound {sound?'on':'off'}</button></div>
 <div className="moment"><span className="tiny-heart">♥</span><p>{descriptions[room.mode]||descriptions.idle}</p><span className="mode-label">{room.mode==='idle'?'TOGETHER':room.mode.toUpperCase()}</span></div>
 <div className="ambience">{tools.map(({a,label,I,on})=><button key={a} aria-pressed={on} disabled={busy} onClick={()=>go(a)} className={on?'active':''}><I size={17}/>{label}<span className="toggle-dot"/></button>)}</div>
 <RoomChat roomKey={key} open={chatOpen} onOpenChange={setChatOpen}/></section><aside className="sidebar"><section className="control-card"><span className="eyebrow">MAKE YOURSELF AT HOME</span><h2>A little closer</h2><div className="character-picker" aria-label="Choose who to control">{(['boy','girl'] as Person[]).map(p=><button key={p} className={person===p?'chosen':''} onClick={()=>choose(p)} aria-pressed={person===p}><img src={'/sprites/'+p+'-0.png'} alt=""/><span>{room.names[p]}</span>{person===p&&<Check size={13}/>}</button>)}</div><p className="control-help">You’re moving {room.names[person]}.<br/>Little moments bring you both together.</p><div className="affection-grid">{[{a:'hug',label:'Hug',I:HandHeart},{a:'kiss',label:'Kiss',I:Heart},{a:'cuddle',label:'Cuddle',I:Sofa},{a:'dance',label:'Dance',I:Music2}].map(({a,label,I})=><button className={room.mode===a?'active':''} key={a} disabled={busy} onClick={()=>go(a)}><I size={23}/><span>{label}</span></button>)}</div><button className="bedtime" disabled={busy} onClick={()=>go(room.mode==='sleep'?'wake':'sleep')}><Moon size={18}/>{room.mode==='sleep'?'Wake up together':'Fall asleep together'}<span>✦</span></button></section>
 <section className="notes-card"><div className="card-heading"><Mail size={18}/><h2>A note for you</h2></div>{room.notes[0]?<><p className="note-preview">{room.notes[0].text}</p><span className="note-author">with love, {room.notes[0].by}</span></>:<p className="muted">Leave a little something for the next time they come home.</p>}<button className="text-button" onClick={()=>setModal('notes')}>{room.notes.length?'Read & leave a note':'Leave the first note'} <span>↗</span></button></section>
 <section className="moments-card"><div className="card-heading"><Sparkles size={17}/><h2>Little moments</h2></div>{room.memories.length?room.memories.slice(0,3).map((m,i)=><div className="memory" key={m.at+'-'+i}><i/><div><p>{m.text}</p><span>{new Date(m.at).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</span></div></div>):<p className="muted">Our story starts with a little hello.</p>}</section><p className="footer-note">The lights, the hugs, the little things.<br/>Right where we left them. ♡</p></aside></div>
 <Dialog open={!!modal} onOpenChange={open=>{if(!open)setModal('')}}><DialogContent className="room-dialog"><DialogTitle>{modal==='notes'?'Letters left for you':modal==='settings'?'Make it ours':'Invite your person'}</DialogTitle><DialogDescription>{modal==='notes'?'A little love, waiting here for later.':modal==='settings'?'The names that make this place home.':'Anyone with this room link can join and change this room.'}</DialogDescription>
 {modal==='notes'&&<><form onSubmit={async e=>{e.preventDefault();try{await act('note',{text:draft});setDraft('')}catch{}}}><label htmlFor="note">Your note</label><textarea id="note" maxLength={500} value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Something I wanted you to know…" required/><button className="primary-button" disabled={busy||!draft.trim()}>Leave with love <Heart size={15}/></button></form><div className="letters">{room.notes.map((n,i)=><article key={n.at+'-'+i}><p>{n.text}</p><small>{n.by} · {new Date(n.at).toLocaleDateString()}</small></article>)}</div></>}
 {modal==='settings'&&<form onSubmit={async e=>{e.preventDefault();try{await act('names',names);setModal('')}catch{}}}><label htmlFor="boy-name">His name</label><input id="boy-name" required maxLength={24} value={names.boy} onChange={e=>setNames({...names,boy:e.target.value})}/><label htmlFor="girl-name">Her name</label><input id="girl-name" required maxLength={24} value={names.girl} onChange={e=>setNames({...names,girl:e.target.value})}/><button className="primary-button" disabled={busy}>Save our names</button></form>}
 {modal==='share'&&<input readOnly value={typeof location==='undefined'?'':location.href} aria-label="Room invitation link" onFocus={e=>e.target.select()}/>}
 </DialogContent></Dialog>{notice&&<div className="notice" role="status">{notice}<button aria-label="Dismiss" onClick={()=>setNotice('')}><X size={14}/></button></div>}
 </main>;
}


